// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"Vertex/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/user/send_email",
				Handler: SendEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/user/showinfo",
				Handler: ShowInfoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SuperAdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/v1/user/setauthority",
					Handler: SetAuthorityHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/v1/user/setstatus",
					Handler: SetStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/user/myinfo",
				Handler: ShowMyInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/user/updateinfo",
				Handler: UpdateInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/user/updatetoken",
				Handler: UpdateTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
