// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"Vertex/app/problem/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/list",
				Handler: ProblemListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/posts",
				Handler: ShouOtherPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/search",
				Handler: SearchHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/problem/collect",
				Handler: CollectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/problem/delete",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/detail",
				Handler: GetProblemDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/getcollect",
				Handler: getCollectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/myposts",
				Handler: GetMyPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/problem/publish",
				Handler: PublishHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/recommend",
				Handler: GetRecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/problem/solve",
				Handler: SolveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/problem/tags",
				Handler: TagListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/v1/problem/audit",
					Handler: AuditHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/problem/auditlist",
					Handler: AuditProblemListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
