// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemPostFieldNames          = builder.RawFieldNames(&ProblemPost{})
	problemPostRows                = strings.Join(problemPostFieldNames, ",")
	problemPostRowsExpectAutoSet   = strings.Join(stringx.Remove(problemPostFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemPostRowsWithPlaceHolder = strings.Join(stringx.Remove(problemPostFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProblemPostIdPrefix = "cache:problemPost:id:"
)

type (
	problemPostModel interface {
		Insert(ctx context.Context, data *ProblemPost) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProblemPost, error)
		Update(ctx context.Context, data *ProblemPost) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProblemPostModel struct {
		sqlc.CachedConn
		table string
	}

	ProblemPost struct {
		Id         uint64       `db:"id"`
		ProblemId  uint64       `db:"problem_id"` // 关联 problem.id
		UserId     uint64       `db:"user_id"`    // 关联 users.id
		Title      string       `db:"title"`      // 帖子标题
		Content    string       `db:"content"`    // 推荐理由/内容
		Solution   string       `db:"solution"`   // 代码/题解
		Status     uint64       `db:"status"`     // 状态: 0-审核中, 1-以发布, 2-已撤销
		ViewNum    uint64       `db:"view_num"`
		CollectNum uint64       `db:"collect_num"`
		CreatedAt  time.Time    `db:"created_at"`
		UpdatedAt  time.Time    `db:"updated_at"`
		DeletedAt  sql.NullTime `db:"deleted_at"`
	}
)

func newProblemPostModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProblemPostModel {
	return &defaultProblemPostModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`problem_post`",
	}
}

func (m *defaultProblemPostModel) Delete(ctx context.Context, id uint64) error {
	problemPostIdKey := fmt.Sprintf("%s%v", cacheProblemPostIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, problemPostIdKey)
	return err
}

func (m *defaultProblemPostModel) FindOne(ctx context.Context, id uint64) (*ProblemPost, error) {
	problemPostIdKey := fmt.Sprintf("%s%v", cacheProblemPostIdPrefix, id)
	var resp ProblemPost
	err := m.QueryRowCtx(ctx, &resp, problemPostIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemPostRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemPostModel) Insert(ctx context.Context, data *ProblemPost) (sql.Result, error) {
	problemPostIdKey := fmt.Sprintf("%s%v", cacheProblemPostIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, problemPostRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProblemId, data.UserId, data.Title, data.Content, data.Solution, data.Status, data.ViewNum, data.CollectNum, data.DeletedAt)
	}, problemPostIdKey)
	return ret, err
}

func (m *defaultProblemPostModel) Update(ctx context.Context, data *ProblemPost) error {
	problemPostIdKey := fmt.Sprintf("%s%v", cacheProblemPostIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemPostRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProblemId, data.UserId, data.Title, data.Content, data.Solution, data.Status, data.ViewNum, data.CollectNum, data.DeletedAt, data.Id)
	}, problemPostIdKey)
	return err
}

func (m *defaultProblemPostModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProblemPostIdPrefix, primary)
}

func (m *defaultProblemPostModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemPostRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProblemPostModel) tableName() string {
	return m.table
}
