// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemFieldNames          = builder.RawFieldNames(&Problem{})
	problemRows                = strings.Join(problemFieldNames, ",")
	problemRowsExpectAutoSet   = strings.Join(stringx.Remove(problemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemRowsWithPlaceHolder = strings.Join(stringx.Remove(problemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProblemIdPrefix  = "cache:problem:id:"
	cacheProblemUrlPrefix = "cache:problem:url:"
)

type (
	problemModel interface {
		Insert(ctx context.Context, data *Problem) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Problem, error)
		FindOneByUrl(ctx context.Context, url string) (*Problem, error)
		Update(ctx context.Context, data *Problem) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProblemModel struct {
		sqlc.CachedConn
		table string
	}

	Problem struct {
		Id          uint64       `db:"id"`
		Title       string       `db:"title"`       // 题目名称
		Source      string       `db:"source"`      // 来源: LeetCode/Luogu等
		Url         string       `db:"url"`         // 核心跳转链接
		Description string       `db:"description"` // 简短描述(可选)
		TagsStr     string       `db:"tags_str"`    // Tag名称快照
		ViewNum     uint64       `db:"view_num"`
		CollectNum  uint64       `db:"collect_num"`
		CreatedAt   time.Time    `db:"created_at"`
		UpdatedAt   time.Time    `db:"updated_at"`
		DeletedAt   sql.NullTime `db:"deleted_at"`
	}
)

func newProblemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProblemModel {
	return &defaultProblemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`problem`",
	}
}

func (m *defaultProblemModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	problemIdKey := fmt.Sprintf("%s%v", cacheProblemIdPrefix, id)
	problemUrlKey := fmt.Sprintf("%s%v", cacheProblemUrlPrefix, data.Url)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, problemIdKey, problemUrlKey)
	return err
}

func (m *defaultProblemModel) FindOne(ctx context.Context, id uint64) (*Problem, error) {
	problemIdKey := fmt.Sprintf("%s%v", cacheProblemIdPrefix, id)
	var resp Problem
	err := m.QueryRowCtx(ctx, &resp, problemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemModel) FindOneByUrl(ctx context.Context, url string) (*Problem, error) {
	problemUrlKey := fmt.Sprintf("%s%v", cacheProblemUrlPrefix, url)
	var resp Problem
	err := m.QueryRowIndexCtx(ctx, &resp, problemUrlKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `url` = ? limit 1", problemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, url); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemModel) Insert(ctx context.Context, data *Problem) (sql.Result, error) {
	problemIdKey := fmt.Sprintf("%s%v", cacheProblemIdPrefix, data.Id)
	problemUrlKey := fmt.Sprintf("%s%v", cacheProblemUrlPrefix, data.Url)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, problemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.Source, data.Url, data.Description, data.TagsStr, data.ViewNum, data.CollectNum, data.DeletedAt)
	}, problemIdKey, problemUrlKey)
	return ret, err
}

func (m *defaultProblemModel) Update(ctx context.Context, newData *Problem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	problemIdKey := fmt.Sprintf("%s%v", cacheProblemIdPrefix, data.Id)
	problemUrlKey := fmt.Sprintf("%s%v", cacheProblemUrlPrefix, data.Url)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Title, newData.Source, newData.Url, newData.Description, newData.TagsStr, newData.ViewNum, newData.CollectNum, newData.DeletedAt, newData.Id)
	}, problemIdKey, problemUrlKey)
	return err
}

func (m *defaultProblemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProblemIdPrefix, primary)
}

func (m *defaultProblemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProblemModel) tableName() string {
	return m.table
}
