// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userSolvedFieldNames          = builder.RawFieldNames(&UserSolved{})
	userSolvedRows                = strings.Join(userSolvedFieldNames, ",")
	userSolvedRowsExpectAutoSet   = strings.Join(stringx.Remove(userSolvedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userSolvedRowsWithPlaceHolder = strings.Join(stringx.Remove(userSolvedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserSolvedIdPrefix              = "cache:userSolved:id:"
	cacheUserSolvedUserIdProblemIdPrefix = "cache:userSolved:userId:problemId:"
)

type (
	userSolvedModel interface {
		Insert(ctx context.Context, data *UserSolved) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserSolved, error)
		FindOneByUserIdProblemId(ctx context.Context, userId uint64, problemId uint64) (*UserSolved, error)
		Update(ctx context.Context, data *UserSolved) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserSolvedModel struct {
		sqlc.CachedConn
		table string
	}

	UserSolved struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`
		ProblemId uint64    `db:"problem_id"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newUserSolvedModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserSolvedModel {
	return &defaultUserSolvedModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_solved`",
	}
}

func (m *defaultUserSolvedModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userSolvedIdKey := fmt.Sprintf("%s%v", cacheUserSolvedIdPrefix, id)
	userSolvedUserIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheUserSolvedUserIdProblemIdPrefix, data.UserId, data.ProblemId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userSolvedIdKey, userSolvedUserIdProblemIdKey)
	return err
}

func (m *defaultUserSolvedModel) FindOne(ctx context.Context, id uint64) (*UserSolved, error) {
	userSolvedIdKey := fmt.Sprintf("%s%v", cacheUserSolvedIdPrefix, id)
	var resp UserSolved
	err := m.QueryRowCtx(ctx, &resp, userSolvedIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userSolvedRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSolvedModel) FindOneByUserIdProblemId(ctx context.Context, userId uint64, problemId uint64) (*UserSolved, error) {
	userSolvedUserIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheUserSolvedUserIdProblemIdPrefix, userId, problemId)
	var resp UserSolved
	err := m.QueryRowIndexCtx(ctx, &resp, userSolvedUserIdProblemIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `problem_id` = ? limit 1", userSolvedRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, problemId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSolvedModel) Insert(ctx context.Context, data *UserSolved) (sql.Result, error) {
	userSolvedIdKey := fmt.Sprintf("%s%v", cacheUserSolvedIdPrefix, data.Id)
	userSolvedUserIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheUserSolvedUserIdProblemIdPrefix, data.UserId, data.ProblemId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userSolvedRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ProblemId)
	}, userSolvedIdKey, userSolvedUserIdProblemIdKey)
	return ret, err
}

func (m *defaultUserSolvedModel) Update(ctx context.Context, newData *UserSolved) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userSolvedIdKey := fmt.Sprintf("%s%v", cacheUserSolvedIdPrefix, data.Id)
	userSolvedUserIdProblemIdKey := fmt.Sprintf("%s%v:%v", cacheUserSolvedUserIdProblemIdPrefix, data.UserId, data.ProblemId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userSolvedRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ProblemId, newData.Id)
	}, userSolvedIdKey, userSolvedUserIdProblemIdKey)
	return err
}

func (m *defaultUserSolvedModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserSolvedIdPrefix, primary)
}

func (m *defaultUserSolvedModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userSolvedRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserSolvedModel) tableName() string {
	return m.table
}
