// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userCollectFieldNames          = builder.RawFieldNames(&UserCollect{})
	userCollectRows                = strings.Join(userCollectFieldNames, ",")
	userCollectRowsExpectAutoSet   = strings.Join(stringx.Remove(userCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userCollectRowsWithPlaceHolder = strings.Join(stringx.Remove(userCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserCollectIdPrefix             = "cache:userCollect:id:"
	cacheUserCollectUserIdTargetIdPrefix = "cache:userCollect:userId:targetId:"
)

type (
	userCollectModel interface {
		Insert(ctx context.Context, data *UserCollect) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserCollect, error)
		FindOneByUserIdTargetId(ctx context.Context, userId uint64, targetId uint64) (*UserCollect, error)
		Update(ctx context.Context, data *UserCollect) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserCollectModel struct {
		sqlc.CachedConn
		table string
	}

	UserCollect struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`
		TargetId  uint64    `db:"target_id"` // problem_id 或 post_id
		CreatedAt time.Time `db:"created_at"`
	}
)

func newUserCollectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserCollectModel {
	return &defaultUserCollectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_collect`",
	}
}

func (m *defaultUserCollectModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userCollectIdKey := fmt.Sprintf("%s%v", cacheUserCollectIdPrefix, id)
	userCollectUserIdTargetIdKey := fmt.Sprintf("%s%v:%v", cacheUserCollectUserIdTargetIdPrefix, data.UserId, data.TargetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userCollectIdKey, userCollectUserIdTargetIdKey)
	return err
}

func (m *defaultUserCollectModel) FindOne(ctx context.Context, id uint64) (*UserCollect, error) {
	userCollectIdKey := fmt.Sprintf("%s%v", cacheUserCollectIdPrefix, id)
	var resp UserCollect
	err := m.QueryRowCtx(ctx, &resp, userCollectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userCollectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCollectModel) FindOneByUserIdTargetId(ctx context.Context, userId uint64, targetId uint64) (*UserCollect, error) {
	userCollectUserIdTargetIdKey := fmt.Sprintf("%s%v:%v", cacheUserCollectUserIdTargetIdPrefix, userId, targetId)
	var resp UserCollect
	err := m.QueryRowIndexCtx(ctx, &resp, userCollectUserIdTargetIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `target_id` = ? limit 1", userCollectRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, targetId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCollectModel) Insert(ctx context.Context, data *UserCollect) (sql.Result, error) {
	userCollectIdKey := fmt.Sprintf("%s%v", cacheUserCollectIdPrefix, data.Id)
	userCollectUserIdTargetIdKey := fmt.Sprintf("%s%v:%v", cacheUserCollectUserIdTargetIdPrefix, data.UserId, data.TargetId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userCollectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.TargetId)
	}, userCollectIdKey, userCollectUserIdTargetIdKey)
	return ret, err
}

func (m *defaultUserCollectModel) Update(ctx context.Context, newData *UserCollect) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userCollectIdKey := fmt.Sprintf("%s%v", cacheUserCollectIdPrefix, data.Id)
	userCollectUserIdTargetIdKey := fmt.Sprintf("%s%v:%v", cacheUserCollectUserIdTargetIdPrefix, data.UserId, data.TargetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userCollectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.TargetId, newData.Id)
	}, userCollectIdKey, userCollectUserIdTargetIdKey)
	return err
}

func (m *defaultUserCollectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserCollectIdPrefix, primary)
}

func (m *defaultUserCollectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userCollectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserCollectModel) tableName() string {
	return m.table
}
