// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuditReq struct {
	PostId          int64  `json:"post_id"`
	Status          int32  `json:"status"` // 1=通过 2=拒绝
	FixProblemTitle string `json:"fix_problem_title"`
}

type CollectReq struct {
	Id     int64  `json:"id"`
	Action string `json:"action"`
}

type CommonResp struct {
	Status int32       `json:"status"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error",omitempty`
	Data   interface{} `json:"data",omitempty`
}

type GetMyPostsReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=20"`
	Status   int64 `form:"status,default=-1"` // -1:全部, 0:待审, 1:已发, 2:撤销
}

type GetPostsReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=20"`
	Id       int64 `form:"id"`
}

type GetProblemDetailReq struct {
	Id int64 `form:"id"`
}

type GetProblemDetailResp struct {
	Status int32         `json:"status"`
	Msg    string        `json:"msg"`
	Error  string        `json:"error",omitempty`
	Total  int64         `json:"total"`
	Data   ProblemDetail `json:"data",omitempty`
}

type GetProblemIdReq struct {
	Id int64 `form:"id"`
}

type ListReq struct {
	Page     int64  `json:"page,default=1"`       // 当前页码
	PageSize int64  `json:"page_size,default=20"` // 每页显示数量
	Keyword  string `json:"keyword,optional"`     // 搜索关键词 (标题/来源)
	TagId    int64  `json:"tag_id,optional"`      // 按标签筛选 (0表示全部)
}

type ListResp struct {
	Status int32         `json:"status"`
	Msg    string        `json:"msg"`
	Error  string        `json:"error",omitempty`
	Total  int64         `json:"total"`
	Data   []ProblemPost `json:"data",omitempty`
}

type ProblemDetail struct {
	Id         int64  `json:"id"`
	ProblemId  int64  `json:"problem_id"` // 关联的原始题目ID
	Title      string `json:"title"`
	Content    string `json:"content"`  // 帖子内容
	Solution   string `json:"solution"` // 代码/题解
	Source     string `json:"source"`
	IsSolved   bool   `json:"is_solved"`   // 当前用户是否已打卡该题
	ProblemUrl string `json:"problem_url"` // 原题链接 (需要关联查 problem 表)
	AuthorId   int64  `json:"author_id"`
	ViewNum    int64  `json:"view_num"`
	Tags       string `json:"tags"`
}

type ProblemIdReq struct {
	Id     int64 `json:"id"`
	PostId int64 `json:"pid"`
}

type ProblemPost struct {
	Id       int64   `json:"id"`
	Title    string  `json:"title"`
	Source   string  `json:"source"`
	Score    float64 `json:"score"`
	Tags     string  `json:"tags"`
	IsSolved bool    `json:"is_solved"`
	AuthorId int64   `json:"authorid"`
}

type PublishReq struct {
	ProblemUrl    string  `json:"problem_url"`
	ProblemTitle  string  `json:"problem_title"`
	ProblemSource string  `json:"problem_source"`
	TagIds        []int64 `json:"tag_ids"`
	Title         string  `json:"title"`
	Content       string  `json:"content"`
	Solution      string  `json:"solution"`
}

type Tag struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Category string `json:"category"`
}

type TagListResp struct {
	Status int32  `json:"status"`
	Msg    string `json:"msg"`
	Error  string `json:"error",omitempty`
	Data   []Tag  `json:"data",omitempty`
}
